version: '3.8'

services:
  web:
    build: .
    container_name: soundbox_web
    restart: unless-stopped
    environment:
      DJANGO_DEBUG: 'False'
      DJANGO_SECRET: 'replace-with-a-long-random-secret'
      DB_NAME: 'soundbox_db'
      DB_USER: 'soundbox_user'
      DB_PASSWORD: 'postgres'
      DB_HOST: 'db'
      DB_PORT: '5432'
      ALLOWED_HOSTS: '141.11.123.238,localhost'
    extra_hosts:
      - "host.docker.internal:host-gateway"
    ports:
      - "8000:8000"
    volumes:
      - static_volume:/app/static
      - media_volume:/app/media
    networks:
      - soundbox_network
  db:
    image: postgres:15
    container_name: soundbox_db
    restart: unless-stopped
    environment:
      POSTGRES_DB: 'soundbox_db'
      POSTGRES_USER: 'soundbox_user'
      POSTGRES_PASSWORD: 'postgres'
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - soundbox_network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB_NAME} -h 0.0.0.0"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  static_volume:
  media_volume:
  db_data:

networks:
  soundbox_network:
    driver: bridge
