version: '3.8'

services:
  web:
    build: .
    container_name: soundbox_web
    restart: unless-stopped
    env_file:
      - .env
    environment:
      - DJANGO_DEBUG=False
      - DJANGO_SECRET
      - DB_NAME
      - DB_USER
      - DB_PASSWORD
      - DB_HOST
      - DB_PORT
    extra_hosts:
      - "host.docker.internal:host-gateway"
    ports:
      - "8000:8000"
    volumes:
      - static_volume:/app/static
    networks:
      - soundbox_network

volumes:
  static_volume:

networks:
  soundbox_network:
    driver: bridge
